[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
image = "0.24.6"
num = "0.4"
num-traits = "0.2"
num-derive = "0.3"